### ISSUE TITLE
Apple Music like docking miniview

### ISSUE THREAD

**Issue by devraj** [danielsaidi/BottomSheet#1]
One of the usecases we have for BottomSheet requires us to roll out a mini view and then follow the same interaction like Apple Music i.e:

- Tap the mini view to reveal the full player 
- Swipe down to dock back into the miniview

![File](https://user-images.githubusercontent.com/5961/119069231-198c9080-ba29-11eb-86b1-d0b5b0228c9e.jpg)

FYI this may also be out of scope for this project.

PS Anomaly would be willing to sponsor the development of this feature.

**Comment by danielsaidi** [comment]
This is possible with the current view, but I think the lib should probably have a view that makes this configuration for you (e.g. a BottomBar with a collapsed view and an expanded one).

**Comment by devraj** [comment]
That would be ideal, that way the `View` can track state and reflect it in the `collapsed` and `expanded` views.

**Comment by danielsaidi** [comment]
I'm sorry for not fixing this yet. June is always super busy for me, but I aim to fix this whenever I get some spare time on my hands.

**Comment by danielsaidi** [comment]
@devraj I have updated the demo to show how you can have an expanded and a collapsed view.
