### ISSUE TITLE
PageViewController swipe ignores SwiftUI's navigationBarHidden(true)

### ISSUE THREAD

**Issue by shywoody** [danielsaidi/BottomSheet#10]
when I swipe while the navigation bar is hidden, it reappears.

**Comment by shywoody** [comment]
be like ,[this](https://stackoverflow.com/questions/69883830/uipageviewcontroller-swipe-ignores-swiftuis-navigationbarhiddentrue), could u give some suggestions？😊

**Comment by danielsaidi** [comment]
Do you have the page controller in a bottom sheet?

**Comment by danielsaidi** [comment]
H! @shywoody! Do you have the page controller inside a bottom sheet?

**Comment by shywoody** [comment]
> H! @shywoody! Do you have the page controller inside a bottom sheet?

im so so sorry ...  i reply to the wrong place. it's other people‘s issue

**Comment by danielsaidi** [comment]
Haha, makes sense! 😃
