### ISSUE TITLE
Does not show in Swift Package Manager

### ISSUE THREAD

**Issue by kunalzigma** [danielsaidi/BottomSheet#11]
Am having swift package manager issue. Whenever i try to add it with this link 
`https://github.com/danielsaidi/BottomSheet.git`
It does not show up in swift package manager.

Secondly, when i add library manually, it shows 
`could not find module 'Bottom Sheet' for target x86_64-apple-ios-simulator`

when i try to add 

`import BottomSheet`

Checked on internet, my device with xcode is with apple silicon m1 imac. Didnt try it on intel mac. But if it is able to add with swift package manager, that is great for me.

**Comment by danielsaidi** [comment]
Hi @kunalzigma 

That's strange!

I tried replacing the local package in the demo project with the latest version:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/429927/153813587-b8fd5da1-424b-4336-989e-e9547655fc9c.png">

It is added correctly:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/429927/153813641-b77b8690-bed0-4622-a41c-f7f4a0541ece.png">

And automatically added to the app target:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/429927/153813770-c99baecf-1f99-4a70-94a7-87edc70a957b.png">

The app runs as expected:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/429927/153813883-b0880ec8-9418-4f4f-a9da-cadfaaa4a967.png">

I'm also on an M1 Mac 🤔

**Comment by kunalzigma** [comment]
Now I see it. Actually, there were two other bottomsheet packages in recently used of my project's swift package manager. I had removed these 2 packages from my project but removing them from recently used did the job. As soon as i removed them from recently used, and entered this link in search, it showed yours and i was able to add it successfully without any issue. I think because of similar names, swift package manager got confused. 
Thank you for your support. 🙏🏻☺️

**Comment by danielsaidi** [comment]
Ah, great - happy to hear that it works now 👍
