### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by BagmetDenis** [danielsaidi/BottomSheet#5]
Hi, how to remove shadow when BottomSheet is hidden?

**Comment by danielsaidi** [comment]
Hi! You should be able to listen to the binding, and adjust the configuration thereafter, but I'm unsure about how this would exactly look.

I can send a code sample when I have less things hanging over me :)

**Comment by danielsaidi** [comment]
@BagmetDenis I am looking at the project now. What do you mean with "hidden"?
