### ISSUE TITLE
Transparent Background on handle?

### ISSUE THREAD

**Issue by jakeround** [danielsaidi/BottomSheet#7]
Hey 👋🏻 

Just a simple styling issue, i'm looking to make `backgroundColor` `dividerColor` both transparent so behind the sheet but I want to keep the handle visible. At full opacity it looks like the properties do work but when set to 0 it looks like there's a base colour behind the sheet any ideas?

![Screenshot 2021-12-29 at 01 08 45](https://user-images.githubusercontent.com/31782753/147619689-4822cef4-0fe6-4a26-a122-02dbcef397a9.png)

**Comment by danielsaidi** [comment]
Hi Jake! 

Interesting - let me take a look!

**Comment by jakeround** [comment]
Sweet thank you! Much appreciated 

Project i'm using BottomSheet in 😄 
[Sonix](https://github.com/jakeround/Sonix)

**Comment by danielsaidi** [comment]
Hi again,

The Sonic app looks amazing!

Regarding the background color, I tried turning down the opacity of the demo colors and then the entire sheet becomes semi-transparent:

![Skärmavbild 2022-01-05 kl  23 04 09](https://user-images.githubusercontent.com/429927/148297295-0697e3ed-b580-4b21-8637-2a03cc9ca2af.jpeg)

So no, there are no additional background colors in the sheet, which corresponds with what the code says. 

Perhaps you have a background color in the sheet content view that you provide?
